### ISSUE TITLE
Support for timeouts

### ISSUE THREAD

**Issue by thetoster** [edrosten/libblepp#10]
Is there any plans to add support for timeout for operations such as connect, read, write?

**Comment by edrosten** [comment]
On 20 April 2017 at 09:57, Bartłomiej Żarnowski <notifications@github.com>
wrote:

> Is there any plans to add support for timeout for operations such as
> connect, read, write?
>
Good question! I believe the kernel provides a timeout for connect, though
it's usually set to a long time. The way I do it is to run in nonblocking
mode and have a timer on the select() or poll() system call. If that
expires before a connect happens, then I enter an error state.

For read and write, it's different. Writes always return unless the buffer
is full (it shouldn't be because enqueuing stuff and GATT don't go well
together).  From the BLE point of view, there are two methods, write_cmd
and write_req. The former gets no response from the device and so I'm not
sure that timeouts are meaningful. The second one gets an acknowledgement
from the BLE device, which is fully async.

Likewise with read: a read happens by issuing a read request, and the reply
comes asynchronously and can take an arbitrarily long time. The best way to
implement a timeout is to have a timer and if it expires before a read
response arrives, to enter an error state.

The fully async model is the most general, and is always going to form the
basis of libble++. I'm currently planning a linear, synchronus model which
wraps it that provides a much simpler interface for the common case.
Naturally that will require those timeouts to be built in.



-Ed

**Comment by edrosten** [comment]
solved?
