### ISSUE TITLE
Library interface

### ISSUE THREAD

**Issue by brokenpylons** [edrosten/libblepp#3]
Hi,

I really like the work you've done so far, finally somebody managed to weed out the glib dependency, great job! The library interface is rather convoluted, though. What do you think about something along the lines of:

BLEPP blepp("connection-string");
bleep.characteristics();
blepp.connect();
blepp.read("uuid");
blepp.write("uuid", data);
blepp.writeRequest("uuid", data, lambda);
blepp.listen("uuid", lambda);
blepp.disconnect(); 

Also I would suggest you switch over to CMake, Autotools are a bit archaic don't you think?
I'm willing to help you out :smile:

**Comment by edrosten** [comment]
On 10 March 2017 at 00:21, Žiga L. <notifications@github.com> wrote:

> Hi,
>
> I really like the work you've done so far, finally somebody managed to
> weed out the glib dependency, great job! The library interface is rather
> convoluted, though.
>

I've structured it as a command/callback system because that's the only
really general way to deal with BLE. For example a read command may take an
arbitrarily long time (seconds, minutes or more) to succeed. However:


> What do you think about something along the lines of:
>

BLEPP blepp("connection-string");
> bleep.characteristics();
> blepp.connect();
> blepp.read("uuid");
> blepp.write("uuid", data);
> blepp.writeRequest("uuid", data, lambda);
> blepp.listen("uuid", lambda);
> blepp.disconnect();
>

Yeah, I like that style, and I've been meaning to esentially add a
BlockingGatt class which wraps the callback one to provide a kind of linear
interface like that. It's on the todo list :)



> Also I would suggest you switch over to CMake, Autotools are a bit archaic
> don't you think?
> I'm willing to help you out 😄
>

Well... I'm not much of a fan of CMake, I must say! For one, it produces
recursive makefiles which are horrible and makes unix platforms kind of
second class citizens. I've also had all sorts of trouble cross compiling
other people's scripts. The main advantage I can see of cmake is that it
can target Windows, but since this package is Linux only (for now, I guess,
but it relies on the Linux bluetooth interface), there's no real advantage.

That said, I'll happily keep a contrib/cmakelists build if you like, but
I'm unlikely to maintain it myself.


-Ed

**Comment by smerkousdavid** [comment]
Hi, I would also be happy to maintain the cmakelist. The amazing thing about cmake is first the cross platform ability (which as you've stated, you don't really need it right now). Also it "autoconfigures" per platform and architecture. Cmake just replaced the UNIX make configure standard. Cmake is extremely easy to change and is easy to read for most project types. This framework is quite popular for libraries because it sets many standards for including with the cmakeconfigs (which doesn't completely require your project to be within cmake, but it's easier to creat). Besides the point, I believe asynchronous is a little difficult for beginners and a EasyBLE (Blocking functions) class would be awesome for quick prototyping or for beginners. Those are just some of my thoughts. Great progress on the library so far!

**Comment by brokenpylons** [comment]
I'm glad you like the idea. The interface I had in mind is actually async (the read method is missing a lambda). However I agree, the synchronous versions of the commands can be provided as well. I looked though the code more carefully and the library needs some work. I would start by encapsulating the socket in a separate class so the library can be unit tested properly. Also I would get a proper library for that instead of a simple macro, I suggest Catch.

@smerkousdavid :+1:

**Comment by brokenpylons** [comment]
The coding style is also inconsistent at times. Would you mind if ran the library though an automated formatter. Maybe clang-format?

**Comment by edrosten** [comment]
@brokenpylons: I don't get how the read method is async. If you provide a lambda, then you'd have to have something that waits for BLE events afterwards, then calls the lambda, which essentially is what the interface is now.

Also, with respect to the coding style, sure if you like, but can you just point them out to me first?
