### ISSUE TITLE
Get rid of boost?

### ISSUE THREAD

**Issue by thetoster** [edrosten/libblepp#8]
Hi,
  This library/project is something which I was searching for some time, but one big disadvantage from my perspective is Boost dependency. I wonder if you consider removing this dependency in future? Since it's used only in one place. Adding boost when I do cross-compilation is really painful.

**Comment by edrosten** [comment]
On 19 April 2017 at 14:45, Bartłomiej Żarnowski <notifications@github.com>
wrote:

> Hi,
> This library/project is something which I was searching for some time, but
> one big disadvantage from my perspective is Boost dependency. I wonder if
> you consider removing this dependency in future? Since it's used only in
> one place. Adding boost when I do cross-compilation is really painful.
>

Hi,

It's likely the dependency will go in the future: optional is ratified for
C++17, and so I'll likely replace it with the std version in a bit.

In the mean time, it's part of the header-only bit of boost, so you won't
actually need to cross compile boost in order to be able to use it. You can
grab a copy of just the headers you need using the "bcp" utility.

-Ed

**Comment by thetoster** [comment]
I checked what I need from boost by using bcp as you suggested:
2 355 915 bytes (3,1 MB on disk) for 340 items
I still believe it's overkill.

**Comment by edrosten** [comment]
Wow, 3Mb! That's a quite astonishing amount for such a simple library.

What I mean is though, don't necessarily check it into the repo, just put
it into a directory somewhere and point your include path at it, when
you're cross compiling.

Despite the header size, it should compile down to almost nothing. And
it'll mean you don't need to cross compile all of boost. 3M of temporary
working space isn't too much I think.

Would that work?

I'm not really sure what a better solution is apart from waiting for C++17
to roll around.



sent from phone.

On 21 Apr 2017 12:13, "Bartłomiej Żarnowski" <notifications@github.com>
wrote:

I checked what I need from boost by using bcp as you suggested:
2 355 915 bytes (3,1 MB on disk) for 340 items
I still believe it's overkill.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/edrosten/libblepp/issues/8#issuecomment-296164137>, or mute
the thread

**Comment by thetoster** [comment]
I already done those steps, but I just giving you my feelings about using boost for such task. I personally prefer not to use much dependencies if there is no need for that. Especially complex frameworks.

**Comment by edrosten** [comment]
I do agree with you in general. In this case though the burden is low enough: you need to store a few meg of headers on disk during building, and no cross compiling for boost is necessary. If you think of a better solution (even a sketch of an idea) please let me know.
