### ISSUE TITLE
Example of write.

### ISSUE THREAD

**Issue by thetoster** [edrosten/libblepp#9]
I started to play with your library, but can't found any example how to write something to BTLE device. I started my experiments from your temperature example and done some modifications, at the end of example I changed

    gatt.connect_blocking(argv[1]);
	for(;;)
		gatt.read_and_process_next();

into:

    gatt.connect_blocking("5C:F8:21:F9:80:BD");
    char* data = "!!#RTH\x0c";
    while(done == false) {
      gatt.read_and_process_next();
    }
    gatt.send_write_request(0x12, (const uint8_t*)data, strlen(data));
    gatt.write_and_process_next();
    while(true) {
      gatt.read_and_process_next();
    }

it works, but the structure is quite ugly. I also use variable "done" placed in discover characteristic callback to determine if I'm connected and have all characteristic enumerated. I didn't find a way to do it in more elegant way, but I got often exeption "Error trying to issue command mid state" Is there any set of functions which I can use to determine where I can do read/write to not cause this exception?

**Comment by edrosten** [comment]
On 20 April 2017 at 09:29, Bartłomiej Żarnowski <notifications@github.com>
wrote:

> I started to play with your library, but can't found any example how to
> write something to BTLE device.
>

That's because I was lazy and didn't document it :(

OK, a couple of things to note. First for read_and_process_next and
write_and_process_next, the read and write there refer specifically to the
low level socket.  That means it's got nothing to do with whether you're
reading something from or writing to a characteristic because either way
both start with a write to the socket.

It's a little unclear :)

Second, those should only be called as the result of a select or poll. As
in you basically need code which does:

"does the state machine wish to perform a write? does the socket allow one?
If yes to both, then write_and_process_next"

likewise for read.


So, you can call the write() method on a characteristic, so if you set up
the standard scan and get the GATT tree, you can then look up the
Characteristic by UUID and call the write_request on that characteristic.

BLE is fully asynchronous and the device might take a LONG time to process
the write. When it does, it'll respond with a write_response callback.
Perversely this is only global for the class. There should be a
per-characteristic response callback option like there is for notify.

Anyway, you have to wait for that callback to arrive. You're not allowed to
issue another write request (or indeed any command) until the BLE device
has responded.

Sorry, that's a brief sketch. I'll knock together an example and put it in
the repo.



-Ed

**Comment by thetoster** [comment]
I need to read this few times and check how to implement :)

But in mean time I found another problem...
The setup for tests looks like:
1. Arduino + HM10 btle module
2. openwrt based board with BTLE

communication comes from 2 -> 1 (write then read)
when I send 1 command "!!!!#RTH1\r" I should get response similar to "VTM(25,26.50)"
my previous code covered this case, but when I try to put this into loop:
Connect to BT, write, read, close connection I got multiple times callback on read

in first attempt I got 1 response as expected. After close/connect nr 2 I got 3x this same response, after 3rd close/connect I got 6x this same response. I believe there is some error with buffers or with my code. I'll attach it to this post.
[main.txt](https://github.com/edrosten/libblepp/files/943193/main.txt)

**Comment by thetoster** [comment]
ok, I found problem. I believe inside close() method should be call to primary_services.clear();

**Comment by edrosten** [comment]
Huh I thought I fixed that. I guess not.

Can you send a pull request with the fix?

-Ed

**Comment by edrosten** [comment]
I've put an example of writing in the examples directory now,
